### ISSUE TITLE
I'm not able to submit post via your API.

### ISSUE THREAD

**Issue by UsagiBo** [MDJ-Mikkel-Djurhuus/hackernews-clone#2]
When I POST JSON file to http://146.185.141.49:8081/post with content: "{"username": "sergei", "post_type": "story", "pwd_hash": "1MHhed3L9i", "post_title": "An alternative to VC: &#34;Selling In&#34;", "post_parent": -1, "hanesst_id": 42, "post_text": "", "post_url": "http://www.venturebeat.com/contributors/2006/10/10/an-alternative-to-vc-selling-in/"}" ,
I get response of type 200 with body : {
"code": "ER_DATA_TOO_LONG",
"errno": 1406,
"sqlMessage": "Data too long for column 'post_url' at row 1",
"sqlState": "22001",
"index": 0,
"sql": "Insert into post (id,username,pwd_hash,hanesst_id,post_parent,post_type,post_title,post_url,post_text,post_time) values (default,'sergei','1MHhed3L9i',42,-1,'story','An alternative to VC: &#34;Selling In&#34;','http://www.venturebeat.com/contributors/2006/10/10/an-alternative-to-vc-selling-in/','',default)"
}

**Comment by MDJ-Mikkel-Djurhuus** [comment]
We've now changed from using varchar(45) to varchar(200) 

Sorry for the late response
