### ISSUE TITLE
I'm not able to submit post via your API

### ISSUE THREAD

**Issue by UsagiBo** [MDJ-Mikkel-Djurhuus/hackernews-clone#3]
When I POST JSON file to http://146.185.141.49:8081/post with content: "{"post_title":"Another audience-driven news site that thinks it will win by paying users ","post_text":"","hanesst_id":47,"post_type":"story","post_parent":-1,"username":"onebeerdave","pwd_hash":"fwozXFe7g0","post_url":"http://business2.blogs.com/business2blog/2006/10/startup_watch_c.html"}" ,
I get response of type 200 with body : "{
"code": "ER_DATA_TOO_LONG",
"errno": 1406,
"sqlMessage": "Data too long for column 'post_title' at row 1",
"sqlState": "22001",
"index": 0,
"sql": "Insert into post (id,username,pwd_hash,hanesst_id,post_parent,post_type,post_title,post_url,post_text,post_time) values (default,'onebeerdave','fwozXFe7g0',47,-1,'story','Another audience-driven news site that thinks it will win by paying users ','http://business2.blogs.com/business2blog/2006/10/startup_watch_c.html','',default)"
}".

**Comment by MDJ-Mikkel-Djurhuus** [comment]
We've now changed from using varchar(45) to varchar(200) 

Sorry for the late response
