### ISSUE TITLE
README.md contains wrong URL for the API to post a new post and a new user

### ISSUE THREAD

**Issue by UsagiBo** [MDJ-Mikkel-Djurhuus/hackernews-clone#4]
Example: You mention "Post ROUTE http://146.185.141.49:8081/post/116 - (116 being the id of story) To post a new post"  but in reality the URL is http://146.185.141.49:8081/post. You also don't describe the required format of the POST body.

**Comment by MDJ-Mikkel-Djurhuus** [comment]
The format is now shown and the typo has been fixed
